apiVersion: v1
kind: Secret
metadata:
  name: {{ include "package-repo.secretName" . }}
  labels:
    {{- include "package-repo.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-keys: {{ .Values.config.apiKeys | join "," | quote }}

{{- if and .Values.config.s3.enabled (not .Values.config.s3.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "package-repo.s3SecretName" . }}
  labels:
    {{- include "package-repo.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.config.s3.accessKeyKey }}: {{ .Values.config.s3.accessKey | quote }}
  {{ .Values.config.s3.secretKeyKey }}: {{ .Values.config.s3.secretKey | quote }}
{{- end }}
